version: "3.9"
services:
  videoretalking:
    container_name: videoretalking
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    build:
      context: "./"
      dockerfile: "./Dockerfile"
    volumes:
      - "./:/work/"
    tty: true
    working_dir: /work/
